pid /tmp/nginx.pid;
error_log /dev/stderr crit;
worker_processes auto;
events { worker_connections 256; }
http {
    access_log off;
    client_body_temp_path /tmp/client_body;
    proxy_temp_path /tmp/proxy;
    fastcgi_temp_path /tmp/fastcgi;
    uwsgi_temp_path /tmp/uwsgi;
    scgi_temp_path /tmp/scgi;
    client_max_body_size 25m;
    client_body_timeout 30s;
    server {
        listen 8080;
        location / {
            proxy_pass http://api:8787;
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
            proxy_request_buffering off;
            proxy_buffering off;
            proxy_read_timeout 30s;
        }
    }
}
